<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputType>WinExe</OutputType>
	</PropertyGroup>

	<PropertyGroup>
		<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
		<NoWarn>1701;1702;1705;1591;1573;CA1031;CA1822</NoWarn>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
		<PathMap>$(MSBuildProjectDirectory)\=WalletAnonTx.Fluent.Desktop</PathMap>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>zkSNACKs Ltd</Authors>
		<Company>zkSNACKs Ltd</Company>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyTitle>AnonTx Wallet Fluent</AssemblyTitle>
		<Description>
			Open-source, non-custodial, privacy focused Bitcoin wallet for Windows, Linux, and Mac. Built-in Tor, coinjoin, payjoin and coin control features.
		</Description>
		<Copyright>MIT</Copyright>
		<PackageId>AnonTx Wallet Fluent</PackageId>
		<AssemblyTitle>AnonTx Wallet</AssemblyTitle>
		<PackageTags>bitcoin-wallet;privacy;bitcoin;dotnet;nbitcoin;cross-platform;zerolink;wallet;wabisabi;coinjoin;tor</PackageTags>
		<PackageProjectUrl>https://github.com/zkSNACKs/WalletAnonTx/</PackageProjectUrl>
		<PackageLicenseUrl>https://github.com/zkSNACKs/WalletAnonTx/blob/master/LICENSE.md</PackageLicenseUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/zkSNACKs/WalletAnonTx/</RepositoryUrl>
		<ApplicationIcon>Assets\AnonTxLogo.ico</ApplicationIcon>
		<PackageIcon>Assets\AnonTxLogo.ico</PackageIcon>
		<Product>AnonTx Wallet Fluent</Product>
		<!-- owners is not supported in MSBuild -->
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.ReactiveUI" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\WalletAnonTx.Fluent\WalletAnonTx.Fluent.csproj" />
		<ProjectReference Include="..\WalletAnonTx\WalletAnonTx.csproj" />
	</ItemGroup>

	<ItemGroup>
		<RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
	</ItemGroup>
</Project>
